CREATE DATABASE IF NOT EXISTS esp_remote;
USE esp_remote;

CREATE TABLE Users (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(255) NOT NULL UNIQUE,
  Password VARCHAR(255) NOT NULL
);

CREATE TABLE Topics (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Topic VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE ACL_Table (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  TopicID INT NOT NULL,
  RW INT NOT NULL,
  FOREIGN KEY (UserID) REFERENCES Users(ID),
  FOREIGN KEY (TopicID) REFERENCES Topics(ID),
  UNIQUE(UserID, TopicID)
);

CREATE TABLE Superusers (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(255) NOT NULL UNIQUE
);
